name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check README
        run: |
          test -f README.md
          grep -q "Healthcheck" README.md

      - name: Success
        run: echo "CI passed"
